name: Test Python Versions
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Format code with Python black
      run: |
        make format
